# -*- coding: utf-8 -*-
"""
Extended CA (Collision Avoidance) application: the run_ca.py scenario (4
free-moving CAVs on TM autopilot + background traffic, bikes, pedestrians;
per-CAV YOLOv8 + LiDAR fusion + Kalman tracking, live ground-truth
validation) integrated with the python_vru_service LDM / VRU Basic Service
and the ns-3 v2x-bridge (simulated 5G NR network, ns-3-dev/scratch/
v2x-bridge). Four application modes (--app-mode):

  1  local CA (default, same as run_ca.py): every CAV runs the PyCA
     collision-avoidance check on its own perception output;
  2  edge CA over 5G: no VAMs; every CAV keeps its detections in its own
     local LDM and uploads them (with its ego state) to the edge server as
     simulated 5G packets through the ns-3 bridge; the edge LDM (object
     matching) + PyCA centralized Collision Avoidance generate the warnings,
     which are sent back to the involved CAVs over the simulated downlink
     and logged in the run metrics files when received;
  3  like 2, but the VRUs (pedestrians and bikes) also run a VRU Basic
     Service that transmits ETSI VAMs (UPER-encoded, sent through ns-3) to
     the edge server as additional information for the collision avoidance;
  4  V2X-only edge CA: the VRUs transmit VAMs exactly as in mode 3, but the
     CAVs upload their own ego state only (no perceived object ever reaches
     the edge) and the edge raises CAV<->VRU risks exclusively -- no CAV<->CAV
     pair is ever checked. Answers "what can a centralized CA achieve from
     cooperative messages alone, without any CAV sensor data?".

The local CA of mode 1 keeps running (and being logged) in modes 2/3/4, so
local and edge collision avoidance can be compared on the same run.

Usage:
    conda activate msvan3t_carla
    # modes 2/3/4 need the ns-3 bridge running first (from the ns-3 root):
    #   ./ns3 run "v2x-bridge --gnbX=-42 --gnbY=25 --maxUes=32"
    cd OpenCDA
    python CA/run_ca_extended.py --model n                   # mode 1
    python CA/run_ca_extended.py --app-mode 2 --seconds 20   # edge CA
    python CA/run_ca_extended.py --app-mode 3                # edge CA + VAMs
    python CA/run_ca_extended.py --app-mode 4                # VAM-only edge CA

Outputs (CA/output/run_<timestamp>/):
    metrics.csv        one line per step per CAV per identified object, as in
                       run_ca.py, plus the edge-warning columns (edge
                       warnings received by that CAV since its previous
                       metrics row; empty in mode 1)
    summary.txt        final error + timing statistics + V2X/edge statistics
    v2x_packets.csv    (modes 2/3/4) one line per simulated packet with its
                       ns-3 outcome (delivered/timeout/...) and latency
    edge_warnings.csv  (modes 2/3/4) one line per edge warning delivered to a
                       CAV over the simulated downlink
    VBS_stats.csv      (modes 3/4) one line per VAM generated by a VRU Basic
                       Service: content of the message (sender, position,
                       speed, heading), time since the previous VAM of that
                       VRU, running average VAM periodicity of that VRU and
                       pooled over all the VRUs, triggering condition
    <Cav>/<camera>_<step>.png   annotated frames (bbox + fused LiDAR cluster)

See CA/PIPELINE.md for the perception pipeline and
CA/python_vru_service/README.md + ns-3-dev/scratch/v2x-bridge/README.md for
the V2X/ns-3 side.
"""

import argparse
import csv
import hashlib
import json
import math
import os
import random
import subprocess
import sys
import time
from datetime import datetime

import cv2
import numpy as np
from omegaconf import OmegaConf

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

import opencda.scenario_testing.utils.sim_api as sim_api
from opencda.core.common.cav_world import CavWorld
from opencda.scenario_testing.utils.yaml_utils import add_current_time

# background actor spawners shared with the dataset generator
from dataset_generator.generate_dataset import (
    spawn_background_traffic, spawn_bikes, spawn_pedestrians)
from CA.experiment_support import spawn_manifest_traffic

from CA.sensors import SensorRig
from CA.detector import YoloDetector
from CA.fusion import CameraLidarFusion, CATEGORIES, suppress_contained
from CA.tracker import VehicleTracker, wrap_deg
from CA.PyCA.t2c import t2c as T2CEngine, NO_COLLISION

# annotation colours per category (BGR)
CATEGORY_COLORS = {'vehicle': (0, 255, 255),      # yellow
                   'bike': (255, 255, 0),         # cyan
                   'pedestrian': (255, 0, 255)}   # magenta
EDGE_DETECTED_ID_STRIDE = 100000

# Track<->GT association category rules (see _associate_tracks_to_gt).
# Round 1 (preferred) matches within the same category; a pedestrian track may
# also claim a bike GT because a CARLA bicycle carries a rider YOLO can see as a
# lone person. Round 2 (compatible) allows only physically plausible category
# confusions -- crucially, a vehicle is NEVER matched to a lone pedestrian.
MATCH_PREFERRED = {
    'vehicle': ('vehicle',),
    'bike': ('bike',),
    'pedestrian': ('pedestrian', 'bike'),
}
MATCH_COMPATIBLE = {
    'vehicle': ('vehicle', 'bike'),
    'bike': ('bike', 'pedestrian', 'vehicle'),
    'pedestrian': ('pedestrian', 'bike'),
}


def _associate_tracks_to_gt(tracks, gt_states, eval_dist):
    """Associate confirmed tracks to ground-truth actors, one-to-one.

    Each GT actor is claimed by at most one track and each track by at most one
    GT actor, resolved greedily by ascending distance (the closest admissible
    track/GT pairs win). A first round matches within the same category
    (MATCH_PREFERRED); a second round, for still-unmatched tracks, allows only
    physically plausible category confusions (MATCH_COMPATIBLE) so a vehicle
    detection is never bound to a lone pedestrian. Returns
    ``{track_id: gt_dict or None}``.

    This replaces the former per-track nearest-GT search, which could (a) bind
    two different tracks to the *same* GT actor and (b) attach a vehicle track
    to an unrelated pedestrian through an unrestricted any-category fallback --
    both of which corrupt the track<->GT identity that the offline
    collision/GT alignment relies on.
    """
    result = {t.track_id: None for t in tracks}
    used_gt = set()
    for compat in (MATCH_PREFERRED, MATCH_COMPATIBLE):
        candidates = []
        for t in tracks:
            if result[t.track_id] is not None:
                continue
            gate = eval_dist[t.category]
            allowed = compat[t.category]
            for g in gt_states:
                if g['id'] in used_gt or g['category'] not in allowed:
                    continue
                d = float(np.linalg.norm(t.position[:2] - g['xy']))
                if d < gate:
                    candidates.append((d, t.track_id, g))
        candidates.sort(key=lambda c: c[0])
        assigned = set()
        for d, tid, g in candidates:
            if tid in assigned or g['id'] in used_gt:
                continue
            result[tid] = g
            assigned.add(tid)
            used_gt.add(g['id'])
    return result


def arg_parse():
    parser = argparse.ArgumentParser(
        description='4-CAV YOLOv8 + LiDAR cooperative awareness demo, with '
                    'optional edge collision avoidance over a simulated 5G '
                    'network (ns-3 v2x-bridge).')
    parser.add_argument('--config', type=str, default='CA/ca_convoy.yaml')
    parser.add_argument('--app-mode', type=int, default=1,
                        choices=[1, 2, 3, 4],
                        help='1 = local CA only (run_ca.py behavior); '
                             '2 = + CAV LDMs, detection upload to the edge '
                             'server via ns-3 5G, edge PyCA collision '
                             'avoidance, warnings back via 5G; '
                             '3 = mode 2 + VRUs transmitting VAMs to the '
                             'edge via 5G; '
                             '4 = edge CA fed only by the VRU VAMs and the '
                             'CAV ego states (CAV detections are never '
                             'uploaded), checking CAV<->VRU pairs only.')
    parser.add_argument('--bridge-host', type=str, default='127.0.0.1',
                        help='ns-3 v2x-bridge control host (modes 2/3/4).')
    parser.add_argument('--bridge-port', type=int, default=5555,
                        help='ns-3 v2x-bridge control UDP port (modes 2/3/4).')
    parser.add_argument('--bridge-wait', type=float, default=0.25,
                        help='max wall seconds spent per tick waiting for '
                             'the ns-3 delivery replies (modes 2/3/4).')
    parser.add_argument('--v2x-verbose', action='store_true',
                        help='per-update V2X prints (LDM inserts, VAM TX, '
                             'per-packet bridge traffic).')
    parser.add_argument('--warning-cooldown', type=float, default=2.0,
                        help='minimum seconds between repeated edge warnings '
                             'for the same unordered pair (default 2.0).')
    parser.add_argument('--no-warning-cooldown', action='store_true',
                        help='disable repeated-pair edge-warning cooldown.')
    isinrange = parser.add_mutually_exclusive_group()
    isinrange.add_argument('--apply-isinrange', dest='apply_isinrange',
                           action='store_true',
                           help='apply the PyCA IsInRange gate to GT and '
                                'on-board collision decisions (default).')
    isinrange.add_argument('--no-isinrange', dest='apply_isinrange',
                           action='store_false',
                           help='reproduce the former GT/on-board behavior '
                                'without the IsInRange gate.')
    fixed_t2c = parser.add_mutually_exclusive_group()
    fixed_t2c.add_argument('--fixed-t2c-threshold',
                           dest='fixed_t2c_threshold', action='store_true',
                           help='use the fixed configured T2C threshold for '
                                'GT and on-board checks (default).')
    fixed_t2c.add_argument('--no-fixed-t2c-threshold',
                           dest='fixed_t2c_threshold', action='store_false',
                           help='reproduce the former speed-scaled GT and '
                                'on-board T2C threshold.')
    parser.set_defaults(apply_isinrange=True, fixed_t2c_threshold=True)
    parser.add_argument('--model', type=str, default=None,
                        choices=['n', 'm', 'x'],
                        help='YOLOv8 capacity (overrides the yaml).')
    parser.add_argument('--seconds', type=int, default=None,
                        help='Override scenario.duration_seconds.')
    parser.add_argument('--seed', type=int, default=None,
                        help='Override world.seed. Use different seeds to '
                             'produce independent scenario repetitions (traffic '
                             'layout, TM behavior and VRU sampling all follow '
                             'this seed) for run-to-run confidence intervals.')
    parser.add_argument('--run-dir', type=str, default=None,
                        help='Explicit raw-output directory. Existing '
                             'completed/application-data directories are '
                             'rejected.')
    parser.add_argument('--traffic-manifest', type=str, default=None,
                        help='JSON traffic manifest to create or strictly '
                             'replay for deterministic comparison runs.')
    parser.add_argument('--create-traffic-manifest', action='store_true',
                        help='Create --traffic-manifest from this run; the '
                             'path must not already exist.')
    parser.add_argument('--save-stride', type=int, default=None,
                        help='Override output.save_stride: save the annotated '
                             'camera frames every N steps, 0 = never (the '
                             'frames are illustrative only, no metric reads '
                             'them, and they dominate the run size).')
    parser.add_argument('--raw-only', action='store_true',
                        help='Collect and validate raw records only; do not '
                             'write the legacy aggregate summary.')
    parser.add_argument('--defer-success-marker', action='store_true',
                        help=argparse.SUPPRESS)
    parser.add_argument('-s', '--host', type=str, default='localhost')
    parser.add_argument('-p', '--port', type=int, default=None,
                        help='CARLA RPC port (overrides the yaml).')
    parser.add_argument('-tm', '--tm_port', type=int, default=8000)
    parser.add_argument('-v', '--version', type=str, default='0.9.12')
    return parser.parse_args()


# ---------------------------------------------------------------------------
def heading_from_north(yaw_deg):
    """CARLA yaw (0 = +x/east, clockwise) -> compass heading in [0, 360) from
    north, the ETSI/VAM convention (see python_vru_service/README.md). Applied
    only to the *logged* heading columns; the collision logic keeps using raw
    yaw differences, which are invariant to this change."""
    return (yaw_deg + 90.0) % 360.0


def collect_gt(world):
    """Ground truth of every dynamic object in the scene.

    Returns full simulator kinematics for every actor; category
    follows the same taxonomy as the detections: 'vehicle' (4+ wheels),
    'bike' (2-wheelers, rider included) and 'pedestrian' (walkers).
    """
    objs = []
    for v in world.get_actors().filter('vehicle.*'):
        wheels = int(v.attributes.get('number_of_wheels', 4))
        category = 'bike' if wheels == 2 else 'vehicle'
        t = v.get_transform()
        center = t.transform(v.bounding_box.location)
        vel = v.get_velocity()
        acc = v.get_acceleration()
        objs.append({'id': v.id, 'category': category,
                     'xy': np.array([center.x, center.y]),
                     'z': center.z,
                     'vx': vel.x, 'vy': vel.y, 'vz': vel.z,
                     'ax': acc.x, 'ay': acc.y, 'az': acc.z,
                     'speed': math.sqrt(vel.x ** 2 + vel.y ** 2 +
                                        vel.z ** 2),
                     'yaw': t.rotation.yaw})
    for w in world.get_actors().filter('walker.pedestrian.*'):
        t = w.get_transform()
        vel = w.get_velocity()
        acc = w.get_acceleration()
        objs.append({'id': w.id, 'category': 'pedestrian',
                     'xy': np.array([t.location.x, t.location.y]),
                     'z': t.location.z,
                     'vx': vel.x, 'vy': vel.y, 'vz': vel.z,
                     'ax': acc.x, 'ay': acc.y, 'az': acc.z,
                     'speed': math.sqrt(vel.x ** 2 + vel.y ** 2 +
                                        vel.z ** 2),
                     'yaw': t.rotation.yaw})
    return objs


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def _git_state(path):
    try:
        revision = subprocess.check_output(
            ['git', '-C', path, 'rev-parse', 'HEAD'],
            stderr=subprocess.STDOUT).decode().strip()
        status = subprocess.check_output(
            ['git', '-C', path, 'status', '--short'],
            stderr=subprocess.STDOUT).decode().splitlines()
        return {'revision': revision, 'dirty': bool(status), 'status': status}
    except (OSError, subprocess.CalledProcessError):
        return {'revision': None, 'dirty': None, 'status': []}


def _write_json(path, value):
    temporary = path + '.tmp'
    with open(temporary, 'w') as handle:
        json.dump(value, handle, indent=2, sort_keys=True)
        handle.write('\n')
    os.replace(temporary, path)


def annotate(image, det, track, gt, ca=None):
    """Draw one fused detection + its track state on a camera frame.

    `ca` is the (t2c, s2c, warning, type) tuple from the PyCA collision
    check: t2c/s2c are printed with the estimates, and a firing warning
    turns the whole box red.
    """
    warning = ca is not None and ca[2]
    color = (0, 0, 255) if warning \
        else CATEGORY_COLORS.get(det.category, (0, 255, 255))
    x1, y1, x2, y2 = [int(v) for v in det.bbox]
    cv2.rectangle(image, (x1, y1), (x2, y2), color, 3 if warning else 2)
    for u, v in det.uv_points.astype(int):
        cv2.circle(image, (u, v), 2, (0, 255, 0), -1)

    lines = ['%s %.2f  (%d lidar pts)' % (det.cls_name, det.conf,
                                          det.n_points)]
    if warning:
        lines.insert(0, 'CA WARNING (%s)' % ca[3])
    if track is not None:
        lines.append('pos  (%.1f, %.1f)' % (track.position[0],
                                            track.position[1]))
        lines.append('spd  %.1f m/s' % track.speed)
        if track.heading is not None:
            lines.append('hdg  %.1f deg' % heading_from_north(track.heading))
        if ca is not None and ca[0] >= 0:
            lines.append('t2c  %.1f s   s2c %.1f m' % (ca[0], ca[1]))
        if gt is not None:
            err = np.linalg.norm(track.position[:2] - gt['xy'])
            lines.append('GT   spd %.1f  hdg %.1f  |dpos| %.2fm'
                         % (gt['speed'], heading_from_north(gt['yaw']), err))
    y_text = max(20, y1 - 8 - 18 * len(lines))
    for line in lines:
        cv2.putText(image, line, (x1, y_text), cv2.FONT_HERSHEY_SIMPLEX,
                    0.55, (0, 0, 0), 3, cv2.LINE_AA)
        cv2.putText(image, line, (x1, y_text), cv2.FONT_HERSHEY_SIMPLEX,
                    0.55, color, 1, cv2.LINE_AA)
        y_text += 18


# ---------------------------------------------------------------------------
def main():
    opt = arg_parse()

    if opt.create_traffic_manifest and not opt.traffic_manifest:
        raise ValueError('--create-traffic-manifest requires '
                         '--traffic-manifest')

    opencda_root = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    cfg_path = opt.config if os.path.isabs(opt.config) \
        else os.path.join(opencda_root, opt.config)
    cfg = OmegaConf.load(cfg_path)
    cfg = add_current_time(cfg)

    if opt.port is not None:
        cfg['world']['client_port'] = opt.port
    capacity = opt.model or str(cfg['detection']['model_capacity'])

    sc = cfg['scenario']
    duration = opt.seconds if opt.seconds is not None \
        else int(sc['duration_seconds'])
    dt = float(cfg['world']['fixed_delta_seconds'])
    total_steps = int(round(duration / dt))

    out_root = cfg['output']['root']
    out_root = out_root if os.path.isabs(out_root) \
        else os.path.join(opencda_root, out_root)
    if opt.run_dir:
        run_dir = opt.run_dir if os.path.isabs(opt.run_dir) \
            else os.path.join(opencda_root, opt.run_dir)
        protected = ('_SUCCESS', 'run_metadata.json', 'metrics.csv', 'gt.csv')
        if any(os.path.exists(os.path.join(run_dir, name))
               for name in protected):
            raise RuntimeError('run directory already contains application '
                               'data: %s' % run_dir)
    else:
        run_dir = os.path.join(
            out_root, 'run_%s' % datetime.now().strftime('%Y%m%d_%H%M%S'))
    os.makedirs(run_dir, exist_ok=True)
    save_stride = int(opt.save_stride) if opt.save_stride is not None \
        else int(cfg['output']['save_stride'])
    print_stride = int(cfg['output']['print_stride'])
    eval_dist = {c: float(cfg['output']['eval_match_dist'][c])
                 for c in CATEGORIES}

    bike_cfg = sc.get('bikes', None) or {}
    ped_cfg = sc.get('pedestrians', None) or {}
    n_background = int(sc.get('background_traffic_num', 0) or 0)

    ca_cfg = cfg.get('collision', None) or {}
    ca_t2c_th = float(ca_cfg.get('t2c_th', 4.8))
    ca_s2c_th = float(ca_cfg.get('s2c_th', 4.2))
    ca_alpha_th = float(ca_cfg.get('alpha_th_deg', 17.0))
    ca_check_rear_end = bool(ca_cfg.get('check_rear_end', False))
    warning_cooldown = 0.0 if opt.no_warning_cooldown \
        else float(opt.warning_cooldown)
    if warning_cooldown < 0:
        raise ValueError('warning cooldown must be non-negative')
    if ca_check_rear_end:
        raise ValueError(
            'Rear-end collision checks are disabled for CA experiments; '
            'set collision.check_rear_end to false')

    # V2X / ns-3 integration (modes 2 and 3): imported only when needed
    # (they require asn1tools + geopy)
    app_mode = int(opt.app_mode)
    if app_mode >= 2:
        from CA.python_vru_service.ns3_bridge_client import Ns3BridgeClient
        from CA.python_vru_service.opencda_v2x import V2XLayer
        from CA.python_vru_service import vam_codec

    print('=== CA: YOLOv8-%s + LiDAR fusion, %d CAVs ==='
          % (capacity, len(sc['cavs'])))
    print('  app mode    : %d (%s)'
          % (app_mode,
             {1: 'local collision avoidance only',
              2: 'edge collision avoidance over ns-3 5G (no VAMs)',
              3: 'edge collision avoidance over ns-3 5G + VRU VAMs',
              4: 'edge collision avoidance from VRU VAMs + CAV ego states '
                 'only (no CAV detections, CAV<->VRU pairs only)'}
             [app_mode]))
    print('  collisions : cross-road only (rear-end disabled)')
    print('  town        : %s' % sc['town'])
    print('  duration    : %ds (%d steps @ %.2fs)'
          % (duration, total_steps, dt))
    print('  background  : %d vehicles, %d bikes, %d pedestrians'
          % (n_background, int(bike_cfg.get('num', 0) or 0),
             int(ped_cfg.get('num', 0) or 0)))
    print('  output      : %s%s'
          % (run_dir,
             '' if save_stride > 0 else ' (annotated frames disabled)'))

    seed = int(opt.seed) if opt.seed is not None \
        else int(cfg['world'].get('seed', 11))
    # Reset application RNGs explicitly after model/config imports. Traffic
    # actor selection uses its own seeded RNG in experiment_support as well.
    random.seed(seed)
    np.random.seed(seed)

    weights_dir = os.path.join(opencda_root,
                               str(cfg['detection']['weights_dir']))

    scenario_manager = None
    cavs = []
    bg_list, bike_list = [], []
    walker_list, walker_controllers = [], []
    bridge, v2x_layer = None, None
    try:
        # ---- world -------------------------------------------------------
        scenario_manager = sim_api.ScenarioManager(
            cfg, apply_ml=False, carla_version=opt.version,
            town=str(sc['town']), cav_world=CavWorld(apply_ml=False),
            carla_host=opt.host, carla_port=int(cfg['world']['client_port']))
        world = scenario_manager.world
        client = scenario_manager.client
        spawn_points = world.get_map().get_spawn_points()

        tm = client.get_trafficmanager(opt.tm_port)
        tm.set_synchronous_mode(True)
        tm.set_random_device_seed(seed)

        # ---- CAVs (independent, free to move on TM autopilot) --------------
        bp_lib = world.get_blueprint_library()
        used_indices = set()
        for cav_def in sc['cavs']:
            bp = bp_lib.find('vehicle.lincoln.mkz_2017')
            bp.set_attribute('color', str(cav_def['color']))
            bp.set_attribute('role_name', str(cav_def['name']))
            sp_idx = int(cav_def['spawn_point_index'])
            used_indices.add(sp_idx)
            sp = spawn_points[sp_idx]

            vehicle = world.spawn_actor(bp, sp)
            world.tick()

            # one YOLO model per CAV (only the first announces itself)
            detector = YoloDetector(
                capacity, weights_dir,
                cfg['detection']['confidence'],
                list(cfg['detection']['classes']),
                quiet=bool(cavs))
            rig = SensorRig(world, vehicle, cfg['sensing'])
            fusion = CameraLidarFusion(cfg['fusion'])
            tracker = VehicleTracker(dt, cfg['tracking'])

            vehicle.set_autopilot(True, opt.tm_port)
            tm.ignore_lights_percentage(
                vehicle, 100.0 if sc['ignore_traffic_lights'] else 0.0)
            tm.auto_lane_change(vehicle, False)
            speed_perc = float(sc.get('target_speed_perc', 0) or 0)
            if speed_perc:
                tm.vehicle_percentage_speed_difference(vehicle, speed_perc)

            cavs.append({'name': str(cav_def['name']), 'vehicle': vehicle,
                         'detector': detector, 'rig': rig, 'fusion': fusion,
                         'tracker': tracker,
                         'ca_engine': T2CEngine(node_id=str(cav_def['name']),
                                                T2C_th=ca_t2c_th),
                         'errors': {c: [] for c in CATEGORIES},
                         'timings': {op: [] for op in
                                     ('detect', 'fuse', 'track', 'ca')},
                         'ca_warnings': 0, 'ca_min_t2c': float('inf'),
                         'unmatched': 0})
            print('  spawned %s at spawn point %d (%.1f, %.1f, yaw %.0f)'
                  % (cav_def['name'], sp_idx, sp.location.x, sp.location.y,
                     sp.rotation.yaw))
            if save_stride > 0:
                os.makedirs(os.path.join(run_dir, str(cav_def['name'])),
                            exist_ok=True)

        # ---- background actors --------------------------------------------
        traffic_manifest = None
        if opt.traffic_manifest:
            manifest_path = opt.traffic_manifest \
                if os.path.isabs(opt.traffic_manifest) \
                else os.path.join(opencda_root, opt.traffic_manifest)
            bg_list, bike_list, walker_list, walker_controllers, \
                traffic_manifest = spawn_manifest_traffic(
                    world, client, tm, opt.tm_port, n_background, bike_cfg,
                    ped_cfg, used_indices, manifest_path,
                    opt.create_traffic_manifest, seed, str(sc['town']))
        else:
            bike_list = spawn_bikes(world, client, opt.tm_port, bike_cfg,
                                    used_indices)
            _, bg_list = spawn_background_traffic(
                world, client, opt.tm_port, n_background,
                exclude_indices=used_indices)
            walker_list, walker_controllers = spawn_pedestrians(
                world, client, ped_cfg, seed=seed)

        # readable name of every spawned actor (used in the gt_name /
        # name CSV columns): Cav1..4, veh_1..N, bike_1..B, ped_1..P
        actor_names = {}
        for cav in cavs:
            actor_names[cav['vehicle'].id] = cav['name']
        for i, v in enumerate(bg_list, 1):
            actor_names[v.id] = 'veh_%d' % i
        for i, b in enumerate(bike_list, 1):
            actor_names[b.id] = 'bike_%d' % i
        for i, w in enumerate(walker_list, 1):
            actor_names[w.id] = 'ped_%d' % i

        cav_station_ids = {cav['name']: 101 + i
                           for i, cav in enumerate(cavs)}
        station_rows = []
        for cav in cavs:
            station_rows.append((cav_station_ids[cav['name']], cav['name'],
                                 cav['vehicle'].id, 'cav', 1))
        for i, w in enumerate(walker_list, 1):
            station_rows.append((1000 + i, 'ped_%d' % i, w.id,
                                 'pedestrian', 1 if app_mode >= 3 else 0))
        for i, b in enumerate(bike_list, 1):
            station_rows.append((1000 + len(walker_list) + i,
                                 'bike_%d' % i, b.id, 'bike',
                                 1 if app_mode >= 3 else 0))
        for i, v in enumerate(bg_list, 1):
            station_rows.append(('', 'veh_%d' % i, v.id, 'vehicle', 0))
        with open(os.path.join(run_dir, 'stations.csv'), 'w', newline='') \
                as station_file:
            station_writer = csv.writer(station_file)
            station_writer.writerow(['station_id', 'name', 'actor_id',
                                     'category', 'connected'])
            station_writer.writerows(station_rows)

        metadata = {
            'schema_version': 1,
            'status': 'collecting',
            'policy': app_mode - 1,
            'app_mode': app_mode,
            # What the edge collision avoidance is allowed to work with: in
            # mode 4 the CAVs upload their ego state only (no perceived
            # object ever reaches the edge) and the edge checks CAV<->VRU
            # pairs exclusively.
            'edge_uses_cav_detections': app_mode != 4,
            'edge_pairs': 'cav_vru_only' if app_mode == 4 else 'all',
            'model': capacity,
            'model_name': {'n': 'nano', 'm': 'medium', 'x': 'extra-large'}[
                capacity],
            'duration_seconds': duration,
            'fixed_delta_seconds': dt,
            'total_steps': total_steps,
            'seed': seed,
            'town': str(sc['town']),
            'traffic_manifest': os.path.abspath(manifest_path)
            if opt.traffic_manifest else None,
            'traffic_manifest_sha256': _sha256(manifest_path)
            if opt.traffic_manifest else None,
            'collision_thresholds': {
                't2c_s': ca_t2c_th, 's2c_m': ca_s2c_th,
                'alpha_deg': ca_alpha_th,
                'check_rear_end': False,
                'apply_isinrange': bool(opt.apply_isinrange),
                'fixed_t2c_threshold': bool(opt.fixed_t2c_threshold)},
            'warning_cooldown': warning_cooldown,
            # Effective annotated-frame stride (0 = frames disabled); the
            # yaml value is in 'config' and can differ when overridden.
            'save_stride': save_stride,
            'later_analysis_defaults': {
                'sensing_ms': dt * 1000.0, 'actuation_ms': 100.0},
            'raw_only': bool(opt.raw_only),
            'source': _git_state(opencda_root),
            'config': OmegaConf.to_container(cfg, resolve=True),
        }
        _write_json(os.path.join(run_dir, 'run_metadata.json'), metadata)

        # ---- V2X layer (modes 2/3/4): LDMs + edge CA + ns-3 bridge -----------
        # The stable actor names above (Cav1..4, ped_1..P, bike_1..B) are the
        # origin_IDs used on the ns-3 bridge for the whole run.
        if app_mode >= 2:
            # VAM redundancy logic uses Python's RNG; keep it reproducible and
            # independent from manifest creation/replay details.
            random.seed(seed + 1000)
            bridge = Ns3BridgeClient(opt.bridge_host, opt.bridge_port,
                                     verbose=opt.v2x_verbose)
            vru_defs = [('ped_%d' % i, w, vam_codec.STATION_TYPE_PEDESTRIAN)
                        for i, w in enumerate(walker_list, 1)]
            vru_defs += [('bike_%d' % i, b, vam_codec.STATION_TYPE_CYCLIST)
                         for i, b in enumerate(bike_list, 1)]
            v2x_layer = V2XLayer(
                bridge, app_mode, world.get_map(),
                [(cav['name'], cav['vehicle']) for cav in cavs], vru_defs,
                {'t2c_th': ca_t2c_th, 's2c_th': ca_s2c_th,
                 'alpha_th_deg': ca_alpha_th,
                 'check_rear_end': False,
                 'warning_cooldown': warning_cooldown},
                run_dir, pump_wait_s=opt.bridge_wait,
                quiet=not opt.v2x_verbose)

        # ---- warmup --------------------------------------------------------
        for _ in range(int(sc['warmup_steps'])):
            world.tick()
        # drain stale sensor frames so the loop starts aligned
        frame = world.tick()
        for cav in cavs:
            cav['rig'].fetch(frame)

        # ---- metrics csv ---------------------------------------------------
        # one line per step per CAV per identified (confirmed) object;
        # ground-truth columns are empty when no GT object matches. The
        # t_*_ms columns repeat, on every row of the same step+CAV, the
        # wall-clock time that CAV's pipeline spent on that step, split
        # per operation (YOLO detection / camera-LiDAR fusion / tracking).
        csv_file = open(os.path.join(run_dir, 'metrics.csv'), 'w', newline='')
        writer = csv.writer(csv_file)
        # The edge_warn_* columns (modes 2/3/4, empty in mode 1) repeat, on
        # every row of the same step+CAV, the edge warnings delivered to
        # that CAV over the simulated 5G downlink since its previous
        # metrics row (count, last warning's type/t2c/s2c/downlink latency).
        writer.writerow(['step', 'sim_time', 'cav', 'track_id',
                         'edge_object_id', 'category',
                         'est_x', 'est_y', 'est_vx', 'est_vy',
                         'est_speed', 'est_heading', 'ego_gt_distance',
                         'gt_id', 'gt_name', 'gt_category', 'gt_x', 'gt_y',
                         'gt_vx', 'gt_vy', 'gt_ax', 'gt_ay',
                         'gt_speed', 'gt_heading',
                         'err_pos', 'err_speed', 'err_heading',
                         't2c', 's2c', 'in_range', 'ca_warning', 'ca_type',
                         't_detect_ms', 't_fuse_ms', 't_track_ms',
                         't_ca_ms', 't_total_ms',
                         'edge_warnings', 'edge_warn_type', 'edge_warn_t2c',
                         'edge_warn_s2c', 'edge_warn_latency_ms'])

        # per-step ground truth of every dynamic object (offline analysis)
        gt_file = open(os.path.join(run_dir, 'gt.csv'), 'w', newline='')
        gt_writer = csv.writer(gt_file)
        gt_writer.writerow(['step', 'sim_time', 'id', 'name', 'category',
                            'x', 'y', 'z', 'vx', 'vy', 'vz', 'ax', 'ay',
                            'az', 'speed', 'heading'])

        # Ground-truth CAA reference: the same analytic collision algorithm,
        # fed solely with simulator kinematics for both parties.
        gt_ca_file = open(os.path.join(run_dir, 'gt_ca.csv'), 'w', newline='')
        gt_ca_writer = csv.writer(gt_ca_file)
        gt_ca_writer.writerow(['step', 'sim_time', 'cav', 'cav_actor_id',
                               'other_id', 'other_name', 'other_category',
                               'distance_m', 't2c', 's2c', 'in_range',
                               'gt_ca_warning', 'ca_type'])

        association_file = open(
            os.path.join(run_dir, 'track_associations.csv'), 'w', newline='')
        association_writer = csv.writer(association_file)
        association_writer.writerow(
            ['step', 'sim_time', 'cav', 'cav_station_id', 'track_id',
             'edge_object_id', 'gt_id', 'gt_name', 'gt_category',
             'association_distance_m'])

        # dedicated per-step per-CAV wall-clock timing log (one row per CAV
        # per step: YOLO inference, fusion, tracking, local collision
        # avoidance), consumed by CA/analyze_ca_metrics.py to build the
        # end-to-end warning latency
        timing_file = open(os.path.join(run_dir, 'timing.csv'), 'w',
                           newline='')
        timing_writer = csv.writer(timing_file)
        timing_writer.writerow(['step', 'sim_time', 'cav', 't_detect_ms',
                                't_fuse_ms', 't_track_ms', 't_ca_ms'])

        # ---- main loop -----------------------------------------------------
        print('Running %d steps...' % total_steps)
        start = time.time()
        for step in range(total_steps):
            frame = world.tick()
            t_sim = world.get_snapshot().timestamp.elapsed_seconds

            gt_all = collect_gt(world)
            for g in gt_all:
                gt_writer.writerow([step, '%.6f' % t_sim, g['id'],
                                    actor_names.get(g['id'], ''),
                                    g['category'],
                                    '%.6f' % g['xy'][0],
                                    '%.6f' % g['xy'][1], '%.6f' % g['z'],
                                    '%.6f' % g['vx'], '%.6f' % g['vy'],
                                    '%.6f' % g['vz'], '%.6f' % g['ax'],
                                    '%.6f' % g['ay'], '%.6f' % g['az'],
                                    '%.6f' % g['speed'],
                                    '%.6f' % heading_from_north(g['yaw'])])

            gt_by_id = {g['id']: g for g in gt_all}
            for cav in cavs:
                ego_gt = gt_by_id[cav['vehicle'].id]
                engine = cav['ca_engine']
                for other in gt_all:
                    if other['id'] == ego_gt['id']:
                        continue
                    # Constant-velocity kinematic model (accelerations forced to
                    # zero) for BOTH parties, identical to the on-board and edge
                    # collision checks. CARLA's instantaneous accelerations are
                    # very noisy and, when fed to the t2c cubic, flip a large
                    # fraction of the warnings; zeroing them everywhere makes the
                    # GT reference, on-board and edge streams strictly comparable.
                    raw_t2c = engine.TimeToCollision(
                        ego_gt['xy'][0], ego_gt['xy'][1],
                        ego_gt['vx'], ego_gt['vy'],
                        0.0, 0.0,
                        other['xy'][0], other['xy'][1],
                        other['vx'], other['vy'], 0.0, 0.0)
                    raw_s2c = engine.computes2c(
                        ego_gt['xy'][0], ego_gt['xy'][1],
                        ego_gt['vx'], ego_gt['vy'],
                        0.0, 0.0,
                        other['xy'][0], other['xy'][1],
                        other['vx'], other['vy'], 0.0, 0.0,
                        raw_t2c) if raw_t2c >= 0 else NO_COLLISION
                    ca_type = 'rear-end' if abs(wrap_deg(
                        ego_gt['yaw'] - other['yaw'])) < ca_alpha_th \
                        else 'cross-road'
                    in_range = engine.IsInRange(
                        ego_gt['xy'][0], ego_gt['xy'][1],
                        ego_gt['vx'], ego_gt['vy'],
                        other['xy'][0], other['xy'][1],
                        other['vx'], other['vy'])
                    range_admitted = in_range or not opt.apply_isinrange
                    if ca_type == 'cross-road':
                        warn_t2c, _ = engine.CheckCollision(
                            ego_gt['xy'][0], ego_gt['xy'][1],
                            ego_gt['vx'], ego_gt['vy'],
                            0.0, 0.0,
                            other['xy'][0], other['xy'][1],
                            other['vx'], other['vy'],
                            0.0, 0.0,
                            s2c_threshold=ca_s2c_th,
                            scale_with_speed=not opt.fixed_t2c_threshold)
                    else:
                        warn_t2c = NO_COLLISION
                    gt_ca_writer.writerow([
                        step, '%.6f' % t_sim, cav['name'], ego_gt['id'],
                        other['id'], actor_names.get(other['id'], ''),
                        other['category'], '%.6f' % np.linalg.norm(
                            ego_gt['xy'] - other['xy']),
                        '%.6f' % raw_t2c if raw_t2c >= 0 else '-1',
                        '%.6f' % raw_s2c if raw_s2c >= 0 else '',
                        '1' if in_range else '0',
                        '1' if range_admitted and warn_t2c != NO_COLLISION else '0',
                        ca_type])

            for cav in cavs:
                rig, fusion = cav['rig'], cav['fusion']
                images, points = rig.fetch(frame)

                t0 = time.perf_counter()
                cam_dets = cav['detector'].detect_batch(images)
                t1 = time.perf_counter()

                world_pts = fusion.lidar_to_world(points, rig.lidar.sensor)
                fused = []
                for i, cam in enumerate(rig.cameras):
                    if not cam_dets[i]:
                        continue
                    dets_2d = suppress_contained(cam_dets[i])
                    uv, depth, wxyz = fusion.project_to_camera(world_pts,
                                                               cam.sensor)
                    fused += fusion.fuse_camera(dets_2d, uv, depth, wxyz,
                                                i, cam.sensor)
                merged = fusion.merge_detections(fused)
                t2 = time.perf_counter()

                tracks = cav['tracker'].step(merged)
                t3 = time.perf_counter()
                # confirmed tracks of this step, consumed by the V2X layer
                # (modes 2/3/4) after the per-CAV processing loop
                cav['last_tracks'] = tracks

                # ---- collision avoidance (PyCA t2c/s2c) -------------------
                # ego state from the simulator (a vehicle knows its own
                # kinematics); tracked objects use the fused position and
                # the Kalman velocity. Constant-velocity model for BOTH ego
                # and objects (ax=ay=0), identical to the GT reference and the
                # edge CA, so the three warning streams stay comparable. (CARLA
                # accelerations are noisy and would otherwise flip a large
                # fraction of the warnings; the ego's true acceleration is no
                # longer used here.)
                ego = cav['vehicle']
                ego_tf = ego.get_transform()
                ego_c = ego_tf.transform(ego.bounding_box.location)
                ego_v = ego.get_velocity()
                engine = cav['ca_engine']
                ca_results = {}
                for track in tracks:
                    px, py = float(track.x[0]), float(track.x[1])
                    tvx, tvy = float(track.x[2]), float(track.x[3])
                    raw_t2c = engine.TimeToCollision(
                        ego_c.x, ego_c.y, ego_v.x, ego_v.y, 0.0, 0.0,
                        px, py, tvx, tvy, 0.0, 0.0)
                    raw_s2c = engine.computes2c(
                        ego_c.x, ego_c.y, ego_v.x, ego_v.y, 0.0, 0.0,
                        px, py, tvx, tvy, 0.0, 0.0, raw_t2c) \
                        if raw_t2c >= 0 else NO_COLLISION
                    # Rear-end pairs retain their diagnostic label and raw
                    # t2c/s2c values, but never enter the warning policy.
                    # (CollisionAvoidanceService.classify); the track's motion
                    # direction stands in for its heading
                    trk_heading = track.heading if track.heading is not None \
                        else math.degrees(math.atan2(tvy, tvx))
                    ca_type = 'rear-end' if abs(wrap_deg(
                        ego_tf.rotation.yaw - trk_heading)) < ca_alpha_th \
                        else 'cross-road'
                    in_range = engine.IsInRange(
                        ego_c.x, ego_c.y, ego_v.x, ego_v.y,
                        px, py, tvx, tvy)
                    range_admitted = in_range or not opt.apply_isinrange
                    if ca_type == 'cross-road':
                        warn_t2c, _ = engine.CheckCollision(
                            ego_c.x, ego_c.y, ego_v.x, ego_v.y,
                            0.0, 0.0,
                            px, py, tvx, tvy, 0.0, 0.0,
                            s2c_threshold=ca_s2c_th,
                            scale_with_speed=not opt.fixed_t2c_threshold)
                    else:
                        warn_t2c = NO_COLLISION
                    warning = range_admitted and warn_t2c != NO_COLLISION
                    if warning:
                        cav['ca_warnings'] += 1
                        cav['ca_min_t2c'] = min(cav['ca_min_t2c'], raw_t2c)
                    ca_results[track.track_id] = (raw_t2c, raw_s2c,
                                                  in_range, warning, ca_type)
                t4 = time.perf_counter()

                t_detect = (t1 - t0) * 1000.0
                t_fuse = (t2 - t1) * 1000.0
                t_track = (t3 - t2) * 1000.0
                t_ca = (t4 - t3) * 1000.0
                cav['timings']['detect'].append(t_detect)
                cav['timings']['fuse'].append(t_fuse)
                cav['timings']['track'].append(t_track)
                cav['timings']['ca'].append(t_ca)
                timing_cols = ['%.1f' % t_detect, '%.2f' % t_fuse,
                               '%.2f' % t_track, '%.2f' % t_ca,
                               '%.1f' % (t_detect + t_fuse + t_track + t_ca)]
                timing_writer.writerow([step, '%.6f' % t_sim, cav['name'],
                                        '%.3f' % t_detect, '%.3f' % t_fuse,
                                        '%.3f' % t_track, '%.3f' % t_ca])
                # edge warnings delivered to this CAV since its previous
                # metrics row (the edge processes step N and its warnings
                # travel the simulated downlink, so they surface on the
                # following step's rows)
                edge_cols = v2x_layer.pop_row_info(cav['name']) \
                    if v2x_layer is not None else ['', '', '', '', '']

                # ---- evaluate against ground truth ------------------------
                ego_id = cav['vehicle'].id
                ego_gt = gt_by_id[ego_id]
                gt_states = [g for g in gt_all if g['id'] != ego_id]
                det2track = {id(t.last_detection): t for t in tracks}
                # One-to-one track<->GT association for this CAV/step: each GT
                # actor is claimed by at most one track and a vehicle track is
                # never bound to a lone pedestrian (see _associate_tracks_to_gt).
                # Consumed below for the metrics/association rows and, offline,
                # for the collision<->GT alignment.
                track2gt = _associate_tracks_to_gt(tracks, gt_states, eval_dist)

                for track in tracks:
                    edge_object_id = cav_station_ids[cav['name']] * \
                        EDGE_DETECTED_ID_STRIDE + int(track.track_id)
                    raw_t2c, raw_s2c, in_range, ca_warn, ca_type = \
                        ca_results[track.track_id]
                    ca_cols = [('%.2f' % raw_t2c) if raw_t2c >= 0 else '-1',
                               ('%.2f' % raw_s2c) if raw_s2c >= 0 else '',
                               '1' if in_range else '0',
                               '1' if ca_warn else '0', ca_type]
                    # GT actor this track was associated to (or None). The
                    # one-to-one assignment was computed once for the whole
                    # step above (see _associate_tracks_to_gt), so it can no
                    # longer double-map a GT actor or bind a vehicle track to
                    # an unrelated pedestrian.
                    best_gt = track2gt[track.track_id]

                    est_heading = '%.1f' % heading_from_north(track.heading) \
                        if track.heading is not None else ''
                    if best_gt is None:
                        cav['unmatched'] += 1
                        association_writer.writerow([
                            step, '%.6f' % t_sim, cav['name'],
                            cav_station_ids[cav['name']], track.track_id,
                            edge_object_id, '', '', '', ''])
                        writer.writerow(
                            [step, '%.6f' % t_sim, cav['name'],
                             track.track_id, edge_object_id, track.category,
                             '%.2f' % track.position[0],
                             '%.2f' % track.position[1],
                             '%.4f' % track.x[2], '%.4f' % track.x[3],
                             '%.2f' % track.speed, est_heading, '',
                             '', '', '', '', '', '', '', '', '', '', '',
                             '', '', ''] +
                            ca_cols + timing_cols + edge_cols)
                        continue

                    err_pos = float(np.linalg.norm(track.position[:2] -
                                                   best_gt['xy']))
                    ego_gt_distance = float(np.linalg.norm(
                        ego_gt['xy'] - best_gt['xy']))
                    err_speed = track.speed - best_gt['speed']
                    # heading is only comparable when the track's velocity
                    # state is mature AND the GT object actually moves (the
                    # motion direction of a stationary object is undefined)
                    err_head = wrap_deg(track.heading - best_gt['yaw']) \
                        if track.heading_valid and best_gt['speed'] >= 1.0 \
                        else float('nan')
                    cav['errors'][track.category].append(
                        (err_pos, err_speed, err_head))
                    association_writer.writerow([
                        step, '%.6f' % t_sim, cav['name'],
                        cav_station_ids[cav['name']], track.track_id,
                        edge_object_id, best_gt['id'],
                        actor_names.get(best_gt['id'], ''),
                        best_gt['category'], '%.6f' % err_pos])
                    writer.writerow(
                        [step, '%.6f' % t_sim, cav['name'], track.track_id,
                         edge_object_id, track.category,
                         '%.2f' % track.position[0],
                         '%.2f' % track.position[1],
                         '%.4f' % track.x[2], '%.4f' % track.x[3],
                         '%.2f' % track.speed, est_heading,
                         '%.6f' % ego_gt_distance,
                         best_gt['id'],
                         actor_names.get(best_gt['id'], ''),
                         best_gt['category'],
                         '%.2f' % best_gt['xy'][0],
                         '%.2f' % best_gt['xy'][1],
                         '%.6f' % best_gt['vx'], '%.6f' % best_gt['vy'],
                         '%.6f' % best_gt['ax'], '%.6f' % best_gt['ay'],
                         '%.2f' % best_gt['speed'],
                         '%.1f' % heading_from_north(best_gt['yaw']),
                         '%.2f' % err_pos, '%.2f' % err_speed,
                         '%.1f' % err_head if not math.isnan(err_head)
                         else ''] + ca_cols + timing_cols + edge_cols)

                # ---- console status ----------------------------------------
                if not opt.raw_only and step % print_stride == 0 and tracks:
                    counts = {c: 0 for c in CATEGORIES}
                    errs = []
                    for track in tracks:
                        counts[track.category] += 1
                        gt = track2gt.get(track.track_id)
                        if gt is not None:
                            errs.append(np.linalg.norm(
                                track.position[:2] - gt['xy']))
                    n_matched = len(errs)
                    print('  [%4d] %s: %d veh, %d bike, %d ped | '
                          'matched %d/%d | mean pos err %s'
                          % (step, cav['name'], counts['vehicle'],
                             counts['bike'], counts['pedestrian'],
                             n_matched, len(tracks),
                             '%.2fm' % np.mean(errs) if errs else 'n/a'))

                # ---- save annotated frames (--save-stride 0 = never) ------
                if save_stride > 0 and step % save_stride == 0:
                    by_cam = {}
                    for det in merged:
                        by_cam.setdefault(det.camera_idx, []).append(det)
                    for cam_idx, dets in by_cam.items():
                        img = images[cam_idx].copy()
                        for det in dets:
                            track = det2track.get(id(det))
                            gt = track2gt.get(track.track_id) \
                                if track is not None else None
                            ca = ca_results.get(track.track_id) \
                                if track is not None else None
                            annotate(img, det, track, gt, ca)
                        cam_name = rig.cameras[cam_idx].name
                        cv2.imwrite(os.path.join(
                            run_dir, cav['name'],
                            '%s_%05d.png' % (cam_name, step)), img)

            # ---- V2X phase (modes 2/3/4): everything over the ns-3 5G net ---
            # 1) refresh the scene on the bridge (radio geometry), 2) upload
            # every CAV's detections (local LDM + edge), 3) step the VRU VAM
            # services (mode 3), 4) resolve the simulated deliveries: the
            # detections/VAMs delivered at the edge feed its LDM + PyCA
            # collision avoidance, whose warnings travel back over the
            # simulated downlink and are logged when delivered.
            if v2x_layer is not None:
                t_sim = world.get_snapshot().timestamp.elapsed_seconds
                v2x_layer.step(step, t_sim,
                               {cav['name']: cav.get('last_tracks', [])
                                for cav in cavs})

        elapsed = time.time() - start
        csv_file.close()
        gt_file.close()
        gt_ca_file.close()
        association_file.close()
        timing_file.close()
        print('Done: %d steps in %.1fs wall clock (%.1f steps/s).'
              % (total_steps, elapsed, total_steps / elapsed))

        # The comparison campaign is intentionally collection-only.  The
        # legacy summary remains available for interactive runs, but raw-only
        # runs merely finalize the V2X writers and defer every aggregate.
        v2x_summary = v2x_layer.finalize() if v2x_layer is not None else []
        if not opt.raw_only:
            lines = ['CA run summary  (YOLOv8-%s per CAV, %d CAVs, %d steps '
                     '@ %.2fs)' % (capacity, len(cavs), total_steps, dt)]
            for cav in cavs:
                total = sum(len(v) for v in cav['errors'].values())
                lines.append('')
                lines.append('%s: %d matched object detections '
                             '(+%d unmatched track steps, mostly static '
                             'scenery vehicles with no GT actor)'
                             % (cav['name'], total, cav['unmatched']))
                t = {op: np.array(v) for op, v in cav['timings'].items()}
                lines.append('  timing/step : detect %.1f ms | fusion %.1f ms '
                             '| tracking %.2f ms | collision %.2f ms | '
                             'total %.1f ms (mean)'
                             % (t['detect'].mean(), t['fuse'].mean(),
                                t['track'].mean(), t['ca'].mean(),
                                t['detect'].mean() + t['fuse'].mean() +
                                t['track'].mean() + t['ca'].mean()))
                if cav['ca_warnings']:
                    lines.append('  CA          : %d warning rows (min t2c '
                                 '%.2f s)' % (cav['ca_warnings'],
                                              cav['ca_min_t2c']))
                else:
                    lines.append('  CA          : no collision warnings')
                for cat in CATEGORIES:
                    errs = cav['errors'][cat]
                    if not errs:
                        lines.append('  %-10s: none detected' % cat)
                        continue
                    pos = np.array([e[0] for e in errs])
                    spd = np.array([e[1] for e in errs])
                    hdg = np.array([e[2] for e in errs
                                    if not math.isnan(e[2])])
                    msg = ('  %-10s: %5d dets | pos mean %.2fm RMSE %.2fm | '
                           'speed RMSE %.2fm/s'
                           % (cat, len(errs), pos.mean(),
                              np.sqrt((pos ** 2).mean()),
                              np.sqrt((spd ** 2).mean())))
                    if len(hdg):
                        msg += ' | heading RMSE %.1fdeg' % \
                               np.sqrt((hdg ** 2).mean())
                    lines.append(msg)
            lines += v2x_summary
            summary = '\n'.join(lines)
            print('\n' + summary)
            with open(os.path.join(run_dir, 'summary.txt'), 'w') as f:
                f.write(summary + '\n')

        metadata['status'] = 'collected'
        metadata['elapsed_wall_seconds'] = elapsed
        _write_json(os.path.join(run_dir, 'run_metadata.json'), metadata)

    finally:
        print('Cleaning up...')
        if bridge is not None:
            # the v2x-bridge keeps running for further experiments; it is
            # stopped with Ctrl-C or a {"msg_type": "shutdown"} datagram
            bridge.close()
        for controller in walker_controllers:
            try:
                controller.stop()
                controller.destroy()
            except Exception:
                pass
        for walker in walker_list:
            try:
                walker.destroy()
            except Exception:
                pass
        for v in bike_list + bg_list:
            try:
                v.set_autopilot(False, opt.tm_port)
                v.destroy()
            except Exception:
                pass
        for cav in cavs:
            try:
                cav['rig'].destroy()
            except Exception:
                pass
            try:
                cav['vehicle'].set_autopilot(False, opt.tm_port)
                cav['vehicle'].destroy()
            except Exception:
                pass
        if scenario_manager is not None:
            scenario_manager.close()
        print('Simulation finished.')

    # Reaching here means collection, file finalization, and actor cleanup all
    # completed without an exception. The batch runner treats this marker as
    # the only resumable-success signal.
    marker_name = '_APPLICATION_SUCCESS' if opt.defer_success_marker \
        else '_SUCCESS'
    with open(os.path.join(run_dir, marker_name), 'w') as marker:
        marker.write('raw data collection complete\n')
    return run_dir


if __name__ == '__main__':
    exit_code = 0
    try:
        main()
    except KeyboardInterrupt:
        print(' - Exited by user.')
        exit_code = 130
    except Exception:
        import traceback
        traceback.print_exc()
        exit_code = 1
    finally:
        # CARLA's Python binding can segfault destroying sensors at
        # interpreter shutdown; exit hard once everything is written.
        sys.stdout.flush()
        sys.stderr.flush()
        os._exit(exit_code)
