#
# vru_basic_service.py
#
# Python porting of the VRU Basic Service, based on the C++ implementation in
# VaN3Twin and OScar (ETSI TS 103 300-3) - see https://github.com/DriveX-devs
#
# The service receives the kinematic status of the ego VRU via
# set_ego_vru_kstatus() (called by other services). It then checks the VAM
# triggering conditions (heading change, position change, speed change, safe
# distances, maximum elapsed time) either periodically every 100 ms or when
# externally triggered via a localhost UDP packet containing the string
# "check" — the mode is selected by the global flag DEFAULT_CHECK_MODE
# (periodic by default). VAMs are generated and UPER-encoded via asn1tools
# using the ASN.1 specifications ETSI-ITS-CDD and VAM-PDU-Description which
# must be available in the directory on this Python file.
#
# If the global flag PROXIMITY_CHECK_ENABLED is True (default), the LDM module
# is imported and the proximity checking ("SAFE DISTANCES" triggering condition
# of the C++ code) is performed by reading the LDM content.
#
# Statistics on the generated VAMs can be collected in a CSV file (one row per
# transmitted VAM) by attaching a VamStatsRecorder to the service through
# set_vam_stats(); a single recorder can be shared by all the VRU Basic
# Services of a scenario, so that it also reports the VAM periodicity pooled
# over every VRU (see the VamStatsRecorder docstring).
#

import csv
import math
import random
import socket
import threading
import time
from dataclasses import dataclass
from enum import Enum
from typing import Optional

try:
    from . import vam_codec
    from . import geo_utils
except ImportError:
    import vam_codec
    import geo_utils

# ---------------------------------------------------------------------------
# Global flags
# ---------------------------------------------------------------------------
CHECK_MODE_PERIODIC = "periodic"
CHECK_MODE_TRIGGERED = "triggered"

# Global flag selecting how the VAM triggering conditions are checked:
# periodically using the real-time clock (every T_CheckVamGen = 100 ms)
# or when an external localhost UDP packet containing the string "check"
# is received. Periodic by default.
DEFAULT_CHECK_MODE = CHECK_MODE_PERIODIC

# Global flag enabling the proximity checking (the check by SAFE DISTANCE in
# VaN3Twin/OScar) performed by reading the content of the LDM. False by default.
PROXIMITY_CHECK_ENABLED = False

# Default localhost UDP port for the external "check" trigger
DEFAULT_TRIGGER_PORT = 48110


class VRUBasicServiceError(Enum):
    """Porting of VRUBasicService_error_t."""
    VAM_NO_ERROR = 0
    VAM_WRONG_INTERVAL = 1
    VAM_ALLOC_ERROR = 2
    VAM_ASN1_UPER_ENC_ERROR = 3
    VAM_CANNOT_SEND = 4


class VRURole(Enum):
    VRU_ROLE_OFF = 0
    VRU_ROLE_ON = 1


class VRUClusteringState(Enum):
    VRU_IDLE = 0
    VRU_ACTIVE_STANDALONE = 1
    VRU_ACTIVE_CLUSTER_LEADER = 2
    VRU_PASSIVE = 3


class TriggCond(Enum):
    """Porting of triggcond_t."""
    NOT_VALID = -1
    DISSEMINATION_START = 0
    MAX_TIME_ELAPSED = 1
    HEADING_CHANGE = 2
    POSITION_CHANGE = 3
    SPEED_CHANGE = 4
    SAFE_DISTANCES = 5


@dataclass
class MinDistance:
    """Porting of distance_t (from VRUdp.h in VaN3Twin/OScar)."""
    longitudinal: float = math.inf
    lateral: float = math.inf
    vertical: float = math.inf
    station_id: int = 0
    station_type: int = -1
    safe_dist: bool = False


class VamStatsRecorder:
    """CSV log of the VAMs generated by one or more VRU Basic Services
    (VBS_stats.csv in the OpenCDA/CA application).

    One row is written for every VAM successfully generated and transmitted,
    carrying:

      - the sender station ID (and an optional human-readable name), plus the
        position, speed and heading as included in the message: they are
        decoded back from the UPER bytes that have just been sent, so they
        carry the ETSI quantization. The position is reported both as
        latitude/longitude (the VAM referencePosition) and, when a
        geo_utils.GeoConverter is available, as x/y in its local cartesian
        frame;
      - the time elapsed since the previous VAM sent by the same VRU (empty
        for the first VAM of that VRU);
      - the average VAM periodicity of that VRU up to this VAM, i.e. the mean
        of its inter-VAM intervals so far;
      - the average VAM periodicity up to this VAM pooled over all the VRUs
        sharing this recorder, i.e. the mean of every inter-VAM interval
        recorded so far, whatever the sender;
      - the triggering condition (a TriggCond name) that caused the tx of the VAM.

    Times follow the clock of the service that generated the VAM: the
    simulation clock when an external time reference is set with
    set_timestamp_callback(), the monotonic wall clock otherwise.

    A single recorder is meant to be shared by every VRU Basic Service of a
    scenario (can be attached with VRUBasicService.set_vam_stats()); it is
    thread-safe, so services running their own dissemination threads can share
    it safely.
    """

    COLUMNS = ["gen_time_s", "sender_id", "sender_name", "station_type",
               "latitude_deg", "longitude_deg", "x_m", "y_m", "speed_ms",
               "heading_deg", "dt_last_vam_s", "avg_period_vru_s",
               "avg_period_all_s", "trigger_condition", "vam_count_vru",
               "vam_count_all"]

    def __init__(self, path, geo_converter=None):
        """path: destination CSV file; geo_converter: optional
        geo_utils.GeoConverter used to express the VAM position in the local
        x/y frame (by default the converter of the sending service is used)."""
        self.path = path
        self.m_geo_converter = geo_converter
        self._lock = threading.RLock()
        self._file = open(path, "w", newline="")
        self._writer = csv.writer(self._file)
        self._writer.writerow(self.COLUMNS)
        self._file.flush()
        # Per-VRU state: station id -> [VAMs sent, sum of intervals [s],
        # number of intervals]
        self._per_vru = {}
        # Pooled state over every VRU sharing the recorder
        self._vams_total = 0
        self._interval_sum = 0.0
        self._interval_count = 0

    @staticmethod
    def _fmt(value, fmt="%.6f"):
        return "" if value is None else fmt % value

    def record(self, service, encoded_vam, now_ms, prev_vam_ms):
        """Log one VAM. Called by VRUBasicService.generate_and_encode_vam()
        after a successful transmission: now_ms is the generation time of this
        VAM and prev_vam_ms the generation time of the previous one (-1 or
        None when this is the first VAM of that VRU), both in milliseconds on
        the service clock."""
        station_id = service.m_station_id
        station_type = service.m_stationtype
        lat = None
        lon = None
        speed = None
        heading = None
        try:
            vam = vam_codec.decode_vam(encoded_vam)
            basic = vam["vam"]["vamParameters"]["basicContainer"]
            hf = vam["vam"]["vamParameters"]["vruHighFrequencyContainer"]
            station_id = vam["header"]["stationId"]
            station_type = basic["stationType"]
            lat = vam_codec.etsi_to_lat_deg(basic["referencePosition"]["latitude"])
            lon = vam_codec.etsi_to_lon_deg(basic["referencePosition"]["longitude"])
            speed = vam_codec.etsi_to_speed_ms(hf["speed"]["speedValue"])
            heading = vam_codec.etsi_to_heading_deg(hf["heading"]["value"])
        except Exception as e:
            # The row is still written: the periodicity statistics do not
            # depend on the message content
            print("[VamStatsRecorder] Warning/BUG: unable to decode a generated VAM (%s)" % e)

        x = None
        y = None
        converter = self.m_geo_converter or service.m_geo_converter
        if lat is not None and lon is not None and converter is not None:
            x, y = converter.latlon_to_xy(lat, lon)

        dt = None
        if prev_vam_ms is not None and prev_vam_ms >= 0:
            dt = (now_ms - prev_vam_ms) / 1000.0

        with self._lock:
            state = self._per_vru.setdefault(station_id, [0, 0.0, 0])
            state[0] += 1
            self._vams_total += 1
            if dt is not None:
                state[1] += dt
                state[2] += 1
                self._interval_sum += dt
                self._interval_count += 1
            avg_vru = state[1] / state[2] if state[2] else None
            avg_all = (self._interval_sum / self._interval_count
                       if self._interval_count else None)
            self._writer.writerow([
                self._fmt(now_ms / 1000.0, "%.3f"), station_id,
                getattr(service, "m_station_label", None) or "", station_type,
                self._fmt(lat, "%.7f"), self._fmt(lon, "%.7f"),
                self._fmt(x, "%.3f"), self._fmt(y, "%.3f"),
                self._fmt(speed, "%.3f"), self._fmt(heading, "%.1f"),
                self._fmt(dt, "%.3f"), self._fmt(avg_vru, "%.4f"),
                self._fmt(avg_all, "%.4f"), service.m_trigg_cond.name,
                state[0], self._vams_total])
            self._file.flush()

    def close(self):
        with self._lock:
            if self._file is not None:
                self._file.close()
                self._file = None


class VRUBasicService:
    # Minimum and maximum time interval between the generation of two
    # consecutive VAMs (ETSI TS 103 300-3)
    T_GenVamMin_ms = 100
    T_GenVamMax_ms = 5000

    def __init__(self, station_id=None, station_type=vam_codec.STATION_TYPE_PEDESTRIAN,
                 check_mode=None, proximity_check=None, ldm=None,
                 trigger_port=DEFAULT_TRIGGER_PORT,
                 ref_lat=0.0, ref_lon=0.0):
        self.m_station_id = station_id
        self.m_stationtype = station_type

        self.m_T_GenVam_ms = self.T_GenVamMax_ms
        self.m_T_CheckVamGen_ms = self.T_GenVamMin_ms

        # Redundancy mitigation state
        self.m_N_GenVam_red = 0
        self.m_N_GenVam_max_red = 2

        # Previous VAM relevant values
        self.m_prev_heading = -1
        self.m_prev_speed = -1
        self.m_prev_pos_x = -1
        self.m_prev_pos_y = -1
        self.m_prev_lat = -1
        self.m_prev_lon = -1

        # Safe distances [m]
        self.m_long_safe_d = -1
        self.m_lat_safe_d = 2.0
        self.m_vert_safe_d = 5.0

        # Triggering condition thresholds (ETSI TS 103 300-3 chap. 8 table 17)
        self.m_heading_threshold_deg = 4.0
        self.m_position_threshold_m = 4.0
        self.m_speed_threshold_ms = 0.5

        self.m_last_vam_gen = -1
        self.m_vam_sent = 0
        self.m_trigg_cond = TriggCond.NOT_VALID

        # Statistics: number of VAMs sent per triggering condition
        self.m_pos_sent = 0
        self.m_speed_sent = 0
        self.m_head_sent = 0
        self.m_safedist_sent = 0
        self.m_time_sent = 0

        self.m_VRU_role = VRURole.VRU_ROLE_ON
        self.m_VRU_clust_state = VRUClusteringState.VRU_IDLE

        # Minimum distances of the nearest pedestrian ([0]) and vehicle ([1])
        self.m_min_dist = []

        # Check mode: instance parameter, falling back to the global flag
        self.m_check_mode = check_mode if check_mode is not None else DEFAULT_CHECK_MODE
        self.m_trigger_port = trigger_port

        # Proximity check: instance parameter, falling back to the global flag
        self.m_proximity_check = (proximity_check if proximity_check is not None
                                  else PROXIMITY_CHECK_ENABLED)
        self.m_LDM = ldm
        if self.m_proximity_check and self.m_LDM is None:
            # Import the LDM module and create an internal LDM instance used
            # for the proximity (safe distances) checking
            try:
                from .ldm import LDM
            except ImportError:
                from ldm import LDM
            self.m_LDM = LDM()

        # Converter used to translate the ego x/y position into lat/lon
        self.m_geo_converter = geo_utils.GeoConverter(ref_lat, ref_lon)

        # Ego VRU kinematic status (set by other services via set_ego_vru_kstatus())
        self._ego_lock = threading.RLock()
        self.m_ego_lat = None
        self.m_ego_lon = None
        self.m_ego_x = None
        self.m_ego_y = None
        self.m_ego_speed = None
        self.m_ego_heading = None
        self.m_ego_acceleration = None

        # VAM transmission and reception callbacks
        self.m_tx_callback = None          # called as tx_callback(encoded_vam_bytes)
        self.m_tx_udp_addr = None          # alternatively, (host, port) UDP destination
        self.m_tx_socket = None
        self.m_vam_rx_callback = None      # called as rx_callback(decoded_vam_dict, from_address)

        # Optional external time reference (e.g. the simulation time of an
        # OpenCDA/CARLA co-simulation): a function returning the current time
        # in seconds (float). When set, it replaces the wall clock in the
        # triggering conditions and in the VAM generationDeltaTime.
        self.m_timestamp_callback = None

        # Optional VAM statistics recorder (VBS_stats.csv), attached with
        # set_vam_stats(); m_station_label is the human-readable name of this
        # VRU reported in the log next to the station ID
        self.m_vam_stats = None
        self.m_station_label = None

        # Dissemination thread management
        self._stop_event = threading.Event()
        self._check_thread = None
        self._trigger_socket = None
        self._started = False

    # ------------------------------------------------------------------
    # Setters
    # ------------------------------------------------------------------
    def set_station_properties(self, station_id, station_type):
        self.m_station_id = station_id
        self.m_stationtype = station_type

    def set_station_id(self, station_id):
        self.m_station_id = station_id

    def set_station_type(self, station_type):
        self.m_stationtype = station_type

    def set_ldm(self, ldm):
        self.m_LDM = ldm

    def set_t_gen_vam(self, t_gen_vam_ms):
        self.m_T_GenVam_ms = t_gen_vam_ms

    def set_t_check_vam_gen(self, t_check_ms):
        self.m_T_CheckVamGen_ms = t_check_ms

    def set_safe_lateral_distance(self, safe_lat_d):
        self.m_lat_safe_d = safe_lat_d

    def set_safe_vertical_distance(self, safe_vert_d):
        self.m_vert_safe_d = safe_vert_d

    def set_reference_position(self, ref_lat, ref_lon):
        """Set the geographical reference point of the local x/y cartesian frame."""
        self.m_geo_converter.set_reference(ref_lat, ref_lon)

    def set_tx_callback(self, tx_callback):
        """Function called with the UPER-encoded VAM (bytes) at every transmission."""
        self.m_tx_callback = tx_callback

    def set_tx_udp(self, host, port):
        """Alternatively to the TX callback, send the encoded VAMs to a UDP destination."""
        self.m_tx_udp_addr = (host, port)
        if self.m_tx_socket is None:
            self.m_tx_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    def add_vam_rx_callback(self, rx_callback):
        """Function called as rx_callback(decoded_vam, from_address) for every received VAM."""
        self.m_vam_rx_callback = rx_callback

    def set_vam_stats(self, recorder, station_label=None):
        """Attach a VamStatsRecorder: one row is then logged for every VAM
        generated by this service. The same recorder can (and normally should)
        be shared by all the VRU Basic Services of the scenario, so that the
        pooled VAM periodicity it reports covers all of them. station_label is
        an optional human-readable name of this VRU (e.g., the CARLA actor
        name) logged next to its station ID."""
        self.m_vam_stats = recorder
        self.m_station_label = station_label

    def set_timestamp_callback(self, timestamp_callback):
        """Set an external time reference for the service: a function returning
        the current time in seconds (float, monotonically increasing).

        This is the equivalent of the "real_time" flag of the C++ implementation:
        when a callback is set, the elapsed-time triggering condition, the
        redundancy mitigation and the VAM generationDeltaTime follow the external
        clock instead of the wall clock. Typical use case: co-simulation with
        OpenCDA/CARLA, passing the CARLA simulation time (see the README)."""
        self.m_timestamp_callback = timestamp_callback

    # ------------------------------------------------------------------
    # Ego VRU kinematic status
    # ------------------------------------------------------------------
    def set_ego_vru_kstatus(self, station_id, station_type, x=None, y=None,
                            lat=None, lon=None, speed=None, heading=None,
                            acceleration=None):
        """Receive the kinematic status of the ego VRU (called by other services).

        The position can be provided either as x/y (meters, local cartesian frame:
        it is converted to lat/lon through geopy using the reference position set
        with set_reference_position()) or directly as lat/lon. Speed [m/s] and
        heading [deg from north] are mandatory; acceleration [m/s^2] is optional.
        """
        if (x is None or y is None) and (lat is None or lon is None):
            raise ValueError("Either x/y or lat/lon must be provided")
        if speed is None or heading is None:
            raise ValueError("speed and heading are mandatory")

        with self._ego_lock:
            self.m_station_id = station_id
            self.m_stationtype = station_type
            if lat is None or lon is None:
                # x/y position: convert it to lat/lon
                lat, lon = self.m_geo_converter.xy_to_latlon(x, y)
            elif x is None or y is None:
                # lat/lon position: keep the x/y local frame coherent
                x, y = self.m_geo_converter.latlon_to_xy(lat, lon)
            self.m_ego_x = x
            self.m_ego_y = y
            self.m_ego_lat = lat
            self.m_ego_lon = lon
            self.m_ego_speed = speed
            # % 360.0 is done only for additional safety, as the heading is expected to be in [0, 360) already
            self.m_ego_heading = heading % 360.0
            self.m_ego_acceleration = acceleration

    # ------------------------------------------------------------------
    # Dissemination management
    # ------------------------------------------------------------------
    def start_vam_dissemination(self, desync_s=0.0):
        if self._started:
            return
        if not (self.m_VRU_clust_state == VRUClusteringState.VRU_IDLE
                and self.m_VRU_role == VRURole.VRU_ROLE_ON):
            return
        with self._ego_lock:
            if self.m_ego_lat is None:
                raise RuntimeError("start_vam_dissemination() called before "
                                   "set_ego_vru_kstatus(): the ego VRU kinematic "
                                   "status is not available")
        self.m_VRU_clust_state = VRUClusteringState.VRU_ACTIVE_STANDALONE
        self._started = True
        self._stop_event.clear()

        if self.m_check_mode == CHECK_MODE_TRIGGERED:
            self._trigger_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self._trigger_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            self._trigger_socket.bind(("127.0.0.1", self.m_trigger_port))
            self._trigger_socket.settimeout(0.1)

        self._check_thread = threading.Thread(target=self._dissemination_loop,
                                              args=(desync_s,), daemon=True)
        self._check_thread.start()

    def terminate_dissemination(self):
        """Porting of terminateDissemination(): stops the service and returns the
        number of VAMs successfully sent."""
        self._stop_event.set()
        if self._check_thread is not None:
            self._check_thread.join(timeout=2.0)
            self._check_thread = None
        if self._trigger_socket is not None:
            self._trigger_socket.close()
            self._trigger_socket = None
        if self.m_tx_socket is not None:
            self.m_tx_socket.close()
            self.m_tx_socket = None
        self._started = False
        self.m_VRU_clust_state = VRUClusteringState.VRU_IDLE
        return self.m_vam_sent

    def _dissemination_loop(self, desync_s):
        if desync_s > 0 and self._stop_event.wait(desync_s):
            return
        self.init_dissemination()

        if self.m_check_mode == CHECK_MODE_PERIODIC:
            # Check the VAM triggering conditions every T_CheckVamGen (100 ms)
            while not self._stop_event.wait(self.m_T_CheckVamGen_ms / 1000.0):
                try:
                    self.check_vam_conditions()
                except Exception as e:
                    print("[VRUBasicService] Error while checking VAM conditions:", e)
        else:
            # Triggered mode: check the conditions when a localhost UDP packet
            # containing the string "check" is received
            while not self._stop_event.is_set():
                try:
                    data, _ = self._trigger_socket.recvfrom(1024)
                except socket.timeout:
                    continue
                except OSError:
                    break
                if data.decode(errors="ignore").strip() == "check":
                    try:
                        self.check_vam_conditions()
                    except Exception as e:
                        print("[VRUBasicService] Error while checking VAM conditions:", e)

    def init_dissemination(self):
        """Porting of initDissemination(): generates the initial VAM
        (DISSEMINATION_START). It is called automatically by
        start_vam_dissemination(); call it directly (once) only when the service
        is stepped manually, i.e. without the internal periodic/triggered loop,
        as in an OpenCDA/CARLA co-simulation where check_vam_conditions() is
        invoked after every simulation tick."""
        self.m_trigg_cond = TriggCond.DISSEMINATION_START
        return self.generate_and_encode_vam()

    # ------------------------------------------------------------------
    # Triggering conditions (porting of checkVamConditions())
    # ------------------------------------------------------------------
    def check_vam_conditions(self):
        now = self._compute_timestamp_ms()
        condition_verified = False
        redundancy_mitigation = False

        # If no initial VAM has been generated before, this is an error
        if self.m_prev_heading == -1 or self.m_prev_speed == -1 or \
                (self.m_prev_pos_x == -1 and self.m_prev_pos_y == -1):
            raise RuntimeError("check_vam_conditions() was called before sending "
                               "any VAM and this is not allowed")

        with self._ego_lock:
            ego_heading = self.m_ego_heading
            ego_speed = self.m_ego_speed
            ego_x, ego_y = self.m_ego_x, self.m_ego_y
            ego_lat, ego_lon = self.m_ego_lat, self.m_ego_lon

        # Check if redundancy mitigation has to be applied
        if self.m_N_GenVam_red == 0:
            redundancy_mitigation = self.check_vam_redundancy_mitigation()

        def can_send():
            return (not redundancy_mitigation and
                    (self.m_N_GenVam_red == 0 or
                     self.m_N_GenVam_red == self.m_N_GenVam_max_red))

        # 1a) The absolute difference between the current heading and the heading
        # included in the previously transmitted VAM exceeds 4 degrees
        head_diff = ego_heading - self.m_prev_heading
        head_diff += -360.0 if head_diff > 180.0 else (360.0 if head_diff < -180.0 else 0.0)
        if abs(head_diff) > self.m_heading_threshold_deg:
            if can_send():
                self.m_N_GenVam_red = 0
                self.m_trigg_cond = TriggCond.HEADING_CHANGE
                if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                    condition_verified = True
                    self.m_head_sent += 1
            else:
                self.m_N_GenVam_red += 1

        # 1b) The distance between the current position and the position included
        # in the previously transmitted VAM exceeds 4 m
        if ego_x is not None and self.m_prev_pos_x != -1:
            pos_diff = math.hypot(ego_x - self.m_prev_pos_x, ego_y - self.m_prev_pos_y)
        else:
            pos_diff = geo_utils.geodesic_distance_m(ego_lat, ego_lon,
                                                     self.m_prev_lat, self.m_prev_lon)
        if not condition_verified and abs(pos_diff) > self.m_position_threshold_m:
            if can_send():
                self.m_N_GenVam_red = 0
                self.m_trigg_cond = TriggCond.POSITION_CHANGE
                if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                    condition_verified = True
                    self.m_pos_sent += 1
            else:
                self.m_N_GenVam_red += 1

        # 1c) The absolute difference between the current speed and the speed
        # included in the previously transmitted VAM exceeds 0.5 m/s
        speed_diff = ego_speed - self.m_prev_speed
        if not condition_verified and abs(speed_diff) > self.m_speed_threshold_ms:
            if can_send():
                self.m_N_GenVam_red = 0
                self.m_trigg_cond = TriggCond.SPEED_CHANGE
                if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                    condition_verified = True
                    self.m_speed_sent += 1
            else:
                self.m_N_GenVam_red += 1

        # 1d) Safe distances (proximity checking through the LDM), performed only
        # if the proximity check flag is enabled
        if self.m_proximity_check and self.m_LDM is not None:
            # Computation of the longitudinal safe distance
            self.m_long_safe_d = abs(ego_speed * (self.T_GenVamMax_ms / 1000.0))

            # Get the minimum distance of other vehicles/pedestrians from the ego VRU
            self.m_min_dist = self.get_min_distance()

            # If the longitudinal distance between the ego VRU and the nearest
            # pedestrian/vehicle is smaller than v*t, the lateral distance smaller
            # than 2 m and the vertical distance smaller than 5 m, a VAM must be
            # transmitted
            if len(self.m_min_dist) != 0:
                veh, ped = self.m_min_dist[1], self.m_min_dist[0]
                if not condition_verified and \
                        veh.longitudinal < self.m_long_safe_d and \
                        veh.lateral < self.m_lat_safe_d and \
                        veh.vertical < self.m_vert_safe_d:
                    self.m_N_GenVam_red = 0
                    self.m_trigg_cond = TriggCond.SAFE_DISTANCES
                    veh.safe_dist = True
                    if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                        condition_verified = True
                        self.m_safedist_sent += 1
                elif not condition_verified and \
                        ped.longitudinal < self.m_long_safe_d and \
                        ped.lateral < self.m_lat_safe_d and \
                        ped.vertical < self.m_vert_safe_d:
                    if can_send():
                        self.m_N_GenVam_red = 0
                        self.m_trigg_cond = TriggCond.SAFE_DISTANCES
                        ped.safe_dist = True
                        if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                            condition_verified = True
                            self.m_safedist_sent += 1
                    else:
                        self.m_N_GenVam_red += 1

        # 2) The time elapsed since the last VAM generation is equal to or greater
        # than T_GenVam
        if not condition_verified and (now - self.m_last_vam_gen) >= self.m_T_GenVam_ms:
            if can_send():
                self.m_N_GenVam_red = 0
                self.m_trigg_cond = TriggCond.MAX_TIME_ELAPSED
                if self.generate_and_encode_vam() == VRUBasicServiceError.VAM_NO_ERROR:
                    condition_verified = True
                    self.m_time_sent += 1
            else:
                self.m_N_GenVam_red += 1

        return condition_verified

    # ------------------------------------------------------------------
    # Proximity checking through the LDM (porting of VRUdp::get_min_distance())
    # ------------------------------------------------------------------
    # IMPORTANT: this does not work fully if CAM reception by VRUs is not implemented!
    def get_min_distance(self):
        """Return [min_distance_pedestrian, min_distance_vehicle] computed over
        the content of the LDM with respect to the ego VRU position."""
        min_distance = [MinDistance(station_type=vam_codec.STATION_TYPE_PEDESTRIAN),
                        MinDistance(station_type=vam_codec.STATION_TYPE_PASSENGER_CAR)]

        with self._ego_lock:
            ego_x, ego_y = self.m_ego_x, self.m_ego_y
            ego_heading = self.m_ego_heading

        if ego_x is None or self.m_LDM is None:
            return min_distance

        heading = ego_heading
        heading += -360.0 if heading > 180.0 else (360.0 if heading < -180.0 else 0.0)
        heading_rad = math.radians(heading)

        # Extract all the stations from the LDM
        with self.m_LDM._lock:
            stations = [self.m_LDM.lookup(sid) for sid in self.m_LDM.get_all_ids()]

        for obj in stations:
            if obj is None or obj.station_id == self.m_station_id:
                continue
            # Get the x/y position of the station (convert from lat/lon if needed)
            if obj.x is not None and obj.y is not None:
                node_x, node_y = obj.x, obj.y
            elif obj.lat is not None and obj.lon is not None:
                node_x, node_y = self.m_geo_converter.latlon_to_xy(obj.lat, obj.lon)
            else:
                continue

            # Computation of the lateral, longitudinal and vertical distances
            lateral = abs((node_x - ego_x) * math.cos(heading_rad))
            longitudinal = abs((node_y - ego_y) * math.cos(heading_rad))
            vertical = 0.0  # Elevation is not stored in this simplified LDM

            idx = 0 if obj.station_type == vam_codec.STATION_TYPE_PEDESTRIAN else 1
            if lateral < min_distance[idx].lateral and \
                    longitudinal < min_distance[idx].longitudinal and \
                    vertical <= min_distance[idx].vertical:
                min_distance[idx].lateral = lateral
                min_distance[idx].longitudinal = longitudinal
                min_distance[idx].vertical = vertical
                min_distance[idx].station_id = obj.station_id

        return min_distance

    # ------------------------------------------------------------------
    # Redundancy mitigation (porting of checkVamRedundancyMitigation())
    # ------------------------------------------------------------------
    def check_vam_redundancy_mitigation(self):
        redundancy_mitigation = False
        now = self._compute_timestamp_ms()

        if self.m_LDM is None or not self.m_proximity_check:
            return False

        with self._ego_lock:
            ego_lat, ego_lon = self.m_ego_lat, self.m_ego_lon
            ego_speed = self.m_ego_speed
            ego_heading = self.m_ego_heading

        ped_heading = ego_heading
        ped_heading += -360.0 if ped_heading > 180.0 else (360.0 if ped_heading < -180.0 else 0.0)

        if now - self.m_last_vam_gen < self.m_N_GenVam_max_red * 5000:
            selected_stations = self.m_LDM.range_select(4.0, ego_lat, ego_lon)

            for obj in selected_stations:
                if redundancy_mitigation:
                    break
                if obj.station_id == self.m_station_id:
                    continue
                if obj.station_type == vam_codec.STATION_TYPE_PEDESTRIAN:
                    speed_diff = (obj.speed if obj.speed is not None else math.inf) - ego_speed
                    near_vru_heading = obj.heading if obj.heading is not None else math.inf
                    near_vru_heading += -360.0 if near_vru_heading > 180.0 else \
                        (360.0 if near_vru_heading < -180.0 else 0.0)
                    heading_diff = near_vru_heading - ped_heading

                    if abs(speed_diff) < 0.5 and abs(heading_diff) < 4:
                        redundancy_mitigation = True
                        self.m_N_GenVam_max_red = int(round(random.random() * 8)) + 2

        return redundancy_mitigation

    # ------------------------------------------------------------------
    # VAM generation (porting of generateAndEncodeVam())
    # ------------------------------------------------------------------
    def generate_and_encode_vam(self):
        with self._ego_lock:
            ego_lat, ego_lon = self.m_ego_lat, self.m_ego_lon
            ego_x, ego_y = self.m_ego_x, self.m_ego_y
            ego_speed = self.m_ego_speed
            ego_heading = self.m_ego_heading
            ego_acceleration = self.m_ego_acceleration

        # Fill the header, the basicContainer and the vruHighFrequencyContainer.
        # The generationDeltaTime is computed as TimestampIts mod 65536.
        vam = {
            "header": {
                "protocolVersion": 3,
                "messageId": vam_codec.FIX_VAMID,
                "stationId": int(self.m_station_id),
            },
            "vam": {
                "generationDeltaTime": self._compute_timestamp_its() % 65536,
                "vamParameters": {
                    "basicContainer": {
                        "stationType": int(self.m_stationtype),
                        "referencePosition": {
                            "latitude": vam_codec.lat_deg_to_etsi(ego_lat),
                            "longitude": vam_codec.lon_deg_to_etsi(ego_lon),
                            "positionConfidenceEllipse": {
                                "semiMajorAxisLength": vam_codec.SEMI_AXIS_LENGTH_UNAVAILABLE,
                                "semiMinorAxisLength": vam_codec.SEMI_AXIS_LENGTH_UNAVAILABLE,
                                "semiMajorAxisOrientation": vam_codec.SEMI_AXIS_ORIENTATION_UNAVAILABLE,
                            },
                            "altitude": {
                                "altitudeValue": vam_codec.ALTITUDE_VALUE_UNAVAILABLE,
                                "altitudeConfidence": "unavailable",
                            },
                        },
                    },
                    "vruHighFrequencyContainer": {
                        "heading": {
                            "value": vam_codec.heading_deg_to_etsi(ego_heading),
                            "confidence": vam_codec.WGS84_ANGLE_CONFIDENCE_UNAVAILABLE,
                        },
                        "speed": {
                            "speedValue": vam_codec.speed_ms_to_etsi(ego_speed),
                            "speedConfidence": vam_codec.SPEED_CONFIDENCE_UNAVAILABLE,
                        },
                        "longitudinalAcceleration": {
                            "longitudinalAccelerationValue":
                                vam_codec.acceleration_ms2_to_etsi(ego_acceleration),
                            "longitudinalAccelerationConfidence":
                                vam_codec.ACCELERATION_CONFIDENCE_UNAVAILABLE,
                        },
                    },
                },
            },
        }

        # VAM UPER encoding
        try:
            encoded = vam_codec.encode_vam(vam)
        except Exception:
            return VRUBasicServiceError.VAM_ASN1_UPER_ENC_ERROR

        # VAM transmission: either through the TX callback or over UDP
        try:
            if self.m_tx_callback is not None:
                self.m_tx_callback(encoded)
            elif self.m_tx_udp_addr is not None and self.m_tx_socket is not None:
                self.m_tx_socket.sendto(encoded, self.m_tx_udp_addr)
        except Exception:
            return VRUBasicServiceError.VAM_CANNOT_SEND

        self.m_vam_sent += 1

        # Store all the "previous" values used in check_vam_conditions()
        # x/y are not included in VAMs; here, however, we also support
        # the provision of x/y positions to enable a more seamless integration
        # with solutions like OpenCDA/CARLA where the ego VRU position is available 
        # in x/y coordinates.
        # Therefore, we do the position triggering check either using x/y or lat/lon,
        # depending on what is available, and hence we need to store also the
        # previous x/y positions for the next check.
        self.m_prev_pos_x = ego_x if ego_x is not None else -1
        self.m_prev_pos_y = ego_y if ego_y is not None else -1
        self.m_prev_lat = ego_lat
        self.m_prev_lon = ego_lon
        self.m_prev_speed = ego_speed
        self.m_prev_heading = ego_heading

        # Store the time in which the last VAM (i.e., this one) has been generated
        prev_vam_gen = self.m_last_vam_gen
        self.m_last_vam_gen = self._compute_timestamp_ms()

        # VAM statistics (one row per generated VAM), if a recorder is attached
        if self.m_vam_stats is not None:
            try:
                self.m_vam_stats.record(self, encoded, self.m_last_vam_gen,
                                        prev_vam_gen)
            except Exception as e:
                print("[VRUBasicService] Error while logging the VAM "
                      "statistics:", e)

        return VRUBasicServiceError.VAM_NO_ERROR

    # ------------------------------------------------------------------
    # VAM reception (porting of receiveVam() + vLDM_handler())
    # ------------------------------------------------------------------
    def receive_vam(self, buffer, from_address=None):
        """Decode a received UPER-encoded VAM; feed the LDM (if available) and
        call the RX callback (if registered)."""
        if self.m_VRU_role == VRURole.VRU_ROLE_OFF:
            return None

        # Try to check if the received packet is really a VAM
        if len(buffer) < 2 or buffer[1] != vam_codec.FIX_VAMID:
            print("[VRUBasicService] Warning: received a message which is not a VAM.")
            return None

        try:
            decoded_vam = vam_codec.decode_vam(buffer)
        except Exception:
            print("[VRUBasicService] Warning: unable to decode a received VAM.")
            return None

        if self.m_LDM is not None:
            # Update the LDM (vLDM_handler())
            self.m_LDM.add_vru_from_vam(buffer, geo_converter=self.m_geo_converter)

        if self.m_vam_rx_callback is not None:
            self.m_vam_rx_callback(decoded_vam, from_address)

        return decoded_vam

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    def _compute_timestamp_ms(self):
        """Monotonic timestamp in milliseconds (porting of computeTimestampUInt64()).
        If an external time reference has been set with set_timestamp_callback()
        (e.g. the OpenCDA/CARLA simulation time), it is used instead of the wall
        clock."""
        if self.m_timestamp_callback is not None:
            return int(self.m_timestamp_callback() * 1000.0)
        return int(time.monotonic() * 1000.0)

    def _compute_timestamp_its(self):
        """Milliseconds since the ITS epoch (2004-01-01T00:00:00.000Z), or since
        the start of the simulation when an external time reference is set."""
        if self.m_timestamp_callback is not None:
            return int(self.m_timestamp_callback() * 1000.0)
        return int((time.time() - vam_codec.ITS_EPOCH_S) * 1000.0)
